#ifndef _STATE_VIEW_HIGHSCORES_H_
#define _STATE_VIEW_HIGHSCORES_H_

void STATE_VIEW_HIGHSCORES_INIT();

void STATE_VIEW_HIGHSCORES_UNINIT();

void STATE_VIEW_HIGHSCORES_LOOP();

void STATE_VIEW_HIGHSCORES_RESIZE();

#endif
